### ISSUE TITLE
Feature Request: Multi-viewport per eye to support LMS, MRS, etc..

### ISSUE THREAD

**Issue by kearwood** [immersive-web/performance-improvements#3]
Currently, we have a limitation of two eyes, returning two sets of projection and view matrices.

To support more efficient rendering, some platforms support features such as Lens Matched Shading and Multi Resolution Shading:

https://developer.nvidia.com/vrworks/graphics/lensmatchedshading
https://developer.nvidia.com/vrworks/graphics/multiresshading

In these cases, additional render targets are created with differing projections.

I would like feedback and to explore ideas surrounding how the WebVR API could be forward-compatible with these rendering approaches.

Ideally, there could be a unified approach to handling other upcoming optimizations, such as foveated rendering.

With the current WebGL 2.0 API, multiple render passes would be required, but this is certainly still beneficial.  We should consider how this API will fit in the context of post-WebGL2 modern graphics apis.

**Comment by kearwood** [comment]
This can also be made an optional feature.

Perhaps the VRDisplay could enumerate the acceptable "lens compression" pre-set formats and the parameters needed for them.  Content could then decide to select one and activate it, rather than having full control over the individual parameters.

Typical profiles to select from may be described:

- Uniform Shading
- Quality Lens Matched Shading
- Conservative Lens Matched Shading
- Aggressive Lens Matched Shading
- Quality Multi-Res Shading
- Conservative Multi-Res Shading
- Aggressive Multi-Res Shading
- Off-Axis projection (Enumerated for C.A.V.E. systems and perhaps Hololens?)

For each of these profiles, there would be an "effective" viewport size and "compressed" viewport size.  The "effective" viewport size would be the size normally used with traditional "Uniform Shading".  This viewport size represents the near-plane of the view frustum.  The "compressed" viewport size represents the actual pixel dimensions after the compression effect takes place.

This means that we may want to report different values for the recommended render target size depending on the shading profile selected.  Perhaps each shading profile would list it's recommended render target size rather than having a single value for the VRDisplay.

It would be acceptable for a UA that does not support Off-Axis, LMS, or MRS to simply enumerate the "Uniform Shading" profile with the normally recommended render target size attached.

**Comment by toji** [comment]
Last week during TPAC we reviewed all of the issues in this repo.

For this particular issue, the consensus seems to be that fixed foveated rendering, such as the type implemented by the Oculus Quest and Go, is a more straightforward way to expose this type of optimization. It could even be implemented using the techniques listed above, but that detail would be hidden away from the developer. Fortunately this is already [a planned feature in the Layers API](https://immersive-web.github.io/layers/#dom-xrcompositionlayer-fixedfoveation).

Aside from that, the more generalized version of this feature that desktop GPUs have been focusing on is [Variable Rate Shading (VRS)](https://developer.nvidia.com/vrworks/graphics/variablerateshading#:~:text=Variable%20Rate%20Shading%20is%20a,their%20HMDs%20for%20foveated%20rendering.) which allows developers to supply a texture with the shading rate desired for various blocks of the scene, such as indicating that the sky should be shaded with a lower resolution than an object the user is holding. This feels like the best direction to investigate going forward, but it's not something uniquely beneficial to WebXR. As a result we would expect such a feature to appear as a WebGL or (more likely) WebGPU extension rather than a WebXR feature.

With that in mind, I'm closing this issue.
