### ISSUE TITLE
Add support for an optional stabilization plane

### ISSUE THREAD

**Issue by rcabanier** [immersive-web/performance-improvements#7]
Can we add another variable `stabilization_depth` to `XRRenderState`?

It defines a distance where the engine will focus its stabilization. Even though it's possible to estimate it from the depth buffer, it's really only the author that really knows this information.

We could specify that non-AR sessions ignore this value.
A reasonable default would be 1.0f and the value must be between `depthNear` and `depthFar`.

**Comment by toji** [comment]
Discussed on a call today and was reminded that we had previously determined that the more common route for this kind of stabilization is to rely on the depth buffer to infer those values. Since we have a clear way of supplying depth buffers to the compositor in our APIs now it seems it's best to continue focusing on having developers provide that for a variety of rendering quality improvements.
